### ISSUE TITLE
Write a blog post about karma

### ISSUE THREAD

**Issue by devth** [yetibot/yetibot.github.io#48]
- announcement of the feature
- some basic usage and examples (with link to docs)
- intent, with maybe historical usage from your own experience with it, and how it can augment culture in a team, or potential application in a larger context like clojurians with many users who don't know eachother + a subset of experts who are willing to help

**Comment by jcorrado** [comment]
Opened PR #49

**Comment by jcorrado** [comment]
http://localhost:4040/blog/2019-05-18-karma-feature-announcement
